run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - gosec
    - revive
    - gosimple
    - typecheck
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

