// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package repo

import (
	"context"
	"time"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, name, currency)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, currency, is_active, kind, created_at
`

type CreateAccountParams struct {
	UserID   int64
	Name     string
	Currency string
}

type CreateAccountRow struct {
	ID        int64
	UserID    int64
	Name      string
	Currency  string
	IsActive  bool
	Kind      string
	CreatedAt time.Time
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.UserID, arg.Name, arg.Currency)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.IsActive,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const createExternalAccount = `-- name: CreateExternalAccount :one
INSERT INTO accounts (user_id, name, currency, kind)
VALUES ($1, 'External', $2, 'external')
RETURNING id, user_id, name, currency, is_active, kind, created_at
`

type CreateExternalAccountParams struct {
	UserID   int64
	Currency string
}

type CreateExternalAccountRow struct {
	ID        int64
	UserID    int64
	Name      string
	Currency  string
	IsActive  bool
	Kind      string
	CreatedAt time.Time
}

func (q *Queries) CreateExternalAccount(ctx context.Context, arg CreateExternalAccountParams) (CreateExternalAccountRow, error) {
	row := q.db.QueryRow(ctx, createExternalAccount, arg.UserID, arg.Currency)
	var i CreateExternalAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.IsActive,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateAccount = `-- name: DeactivateAccount :exec
UPDATE accounts SET is_active = FALSE WHERE id = $1
`

func (q *Queries) DeactivateAccount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, name, currency, is_active, kind, created_at
FROM accounts
WHERE id = $1
`

type GetAccountRow struct {
	ID        int64
	UserID    int64
	Name      string
	Currency  string
	IsActive  bool
	Kind      string
	CreatedAt time.Time
}

func (q *Queries) GetAccount(ctx context.Context, id int64) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.IsActive,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const getExternalAccount = `-- name: GetExternalAccount :one
SELECT id, user_id, name, currency, is_active, kind, created_at
FROM accounts
WHERE user_id = $1 AND kind = 'external'
`

type GetExternalAccountRow struct {
	ID        int64
	UserID    int64
	Name      string
	Currency  string
	IsActive  bool
	Kind      string
	CreatedAt time.Time
}

func (q *Queries) GetExternalAccount(ctx context.Context, userID int64) (GetExternalAccountRow, error) {
	row := q.db.QueryRow(ctx, getExternalAccount, userID)
	var i GetExternalAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.IsActive,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, user_id, name, currency, is_active, kind, created_at
FROM accounts
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAccountsByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

type ListAccountsByUserRow struct {
	ID        int64
	UserID    int64
	Name      string
	Currency  string
	IsActive  bool
	Kind      string
	CreatedAt time.Time
}

func (q *Queries) ListAccountsByUser(ctx context.Context, arg ListAccountsByUserParams) ([]ListAccountsByUserRow, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsByUserRow
	for rows.Next() {
		var i ListAccountsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Currency,
			&i.IsActive,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
