// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exports.sql

package repo

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExport = `-- name: CreateExport :one
INSERT INTO exports (user_id, month, status)
VALUES ($1, $2, 'pending')
RETURNING id, user_id, month, status, file_path, created_at, updated_at
`

type CreateExportParams struct {
	UserID int64
	Month  time.Time
}

func (q *Queries) CreateExport(ctx context.Context, arg CreateExportParams) (Export, error) {
	row := q.db.QueryRow(ctx, createExport, arg.UserID, arg.Month)
	var i Export
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.Status,
		&i.FilePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExportByID = `-- name: GetExportByID :one
SELECT id, user_id, month, status, file_path, created_at, updated_at FROM exports WHERE id = $1
`

func (q *Queries) GetExportByID(ctx context.Context, id int64) (Export, error) {
	row := q.db.QueryRow(ctx, getExportByID, id)
	var i Export
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.Status,
		&i.FilePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPostingsForMonth = `-- name: ListPostingsForMonth :many
SELECT t.id AS transaction_id,
       p.account_id,
       a.name AS account_name,
       t.category_id,
       p.amount_minor,
       t.currency,
       t.occurred_at,
       t.note
FROM postings p
JOIN transactions t ON t.id = p.transaction_id
JOIN accounts a ON a.id = p.account_id
WHERE t.user_id = $1
  AND a.kind = 'normal'
  AND date_trunc('month', t.occurred_at) = date_trunc('month', $2::timestamptz)
ORDER BY t.occurred_at, p.id
`

type ListPostingsForMonthParams struct {
	UserID  int64
	Column2 time.Time
}

type ListPostingsForMonthRow struct {
	TransactionID int64
	AccountID     int64
	AccountName   string
	CategoryID    pgtype.Int8
	AmountMinor   int64
	Currency      string
	OccurredAt    time.Time
	Note          pgtype.Text
}

// Export rows are postings on the user's normal accounts; the offsetting
// external legs would only duplicate every line.
func (q *Queries) ListPostingsForMonth(ctx context.Context, arg ListPostingsForMonthParams) ([]ListPostingsForMonthRow, error) {
	rows, err := q.db.Query(ctx, listPostingsForMonth, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostingsForMonthRow
	for rows.Next() {
		var i ListPostingsForMonthRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.AccountID,
			&i.AccountName,
			&i.CategoryID,
			&i.AmountMinor,
			&i.Currency,
			&i.OccurredAt,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExportStatus = `-- name: UpdateExportStatus :exec
UPDATE exports
SET status = $2, file_path = $3, updated_at = now()
WHERE id = $1
`

type UpdateExportStatusParams struct {
	ID       int64
	Status   string
	FilePath pgtype.Text
}

func (q *Queries) UpdateExportStatus(ctx context.Context, arg UpdateExportStatusParams) error {
	_, err := q.db.Exec(ctx, updateExportStatus, arg.ID, arg.Status, arg.FilePath)
	return err
}
