// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64
	UserID    int64
	Name      string
	Currency  string
	IsActive  bool
	CreatedAt time.Time
}

type BalanceSnapshot struct {
	ID           int64
	AccountID    int64
	AsOfDate     time.Time
	BalanceMinor int64
	CreatedAt    time.Time
}

type Category struct {
	ID        int64
	UserID    int64
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Export struct {
	ID        int64
	UserID    int64
	Month     time.Time
	Status    string
	FilePath  pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type IdempotencyKey struct {
	UserID       int64
	Key          string
	RequestHash  string
	Status       string
	ResponseJson pgtype.Text
	CreatedAt    time.Time
}

type Outbox struct {
	ID          int64
	EventType   string
	Payload     []byte
	CreatedAt   time.Time
	ProcessedAt pgtype.Timestamptz
}

type Transaction struct {
	ID          int64
	UserID      int64
	AccountID   int64
	AmountMinor int64
	Currency    string
	Category    pgtype.Text
	OccurredAt  time.Time
	Note        pgtype.Text
	CreatedAt   time.Time
	CategoryID  pgtype.Int8
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
