// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package repo

import (
	"context"
	"time"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox (event_type, payload)
VALUES ($1, $2)
RETURNING id, created_at
`

type CreateOutboxEventParams struct {
	EventType string
	Payload   []byte
}

type CreateOutboxEventRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (CreateOutboxEventRow, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent, arg.EventType, arg.Payload)
	var i CreateOutboxEventRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
