// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateExport(ctx context.Context, arg CreateExportParams) (Export, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (CreateOutboxEventRow, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateAccount(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetExportByID(ctx context.Context, id int64) (Export, error)
	GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (IdempotencyKey, error)
	GetLatestSnapshot(ctx context.Context, accountID int64) (BalanceSnapshot, error)
	GetMonthlySummary(ctx context.Context, arg GetMonthlySummaryParams) (GetMonthlySummaryRow, error)
	GetSnapshotOnDate(ctx context.Context, arg GetSnapshotOnDateParams) (BalanceSnapshot, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListAccountsByUser(ctx context.Context, arg ListAccountsByUserParams) ([]Account, error)
	ListAllAccountIDs(ctx context.Context) ([]int64, error)
	ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]ListTransactionsByAccountRow, error)
	ListTransactionsForMonth(ctx context.Context, arg ListTransactionsForMonthParams) ([]ListTransactionsForMonthRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkIdempotencySuccess(ctx context.Context, arg MarkIdempotencySuccessParams) error
	SumTransactionsSince(ctx context.Context, arg SumTransactionsSinceParams) (interface{}, error)
	SumTransactionsUpTo(ctx context.Context, arg SumTransactionsUpToParams) (interface{}, error)
	UpdateExportStatus(ctx context.Context, arg UpdateExportStatusParams) error
	UpsertBalanceSnapshot(ctx context.Context, arg UpsertBalanceSnapshotParams) error
	UpsertIdempotencyStart(ctx context.Context, arg UpsertIdempotencyStartParams) (IdempotencyKey, error)
}

var _ Querier = (*Queries)(nil)
