// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error)
	CreateExport(ctx context.Context, arg CreateExportParams) (Export, error)
	CreateExternalAccount(ctx context.Context, arg CreateExternalAccountParams) (CreateExternalAccountRow, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (CreateOutboxEventRow, error)
	CreatePosting(ctx context.Context, arg CreatePostingParams) (Posting, error)
	CreateTransactionHeader(ctx context.Context, arg CreateTransactionHeaderParams) (CreateTransactionHeaderRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateAccount(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (GetAccountRow, error)
	GetExportByID(ctx context.Context, id int64) (Export, error)
	GetExternalAccount(ctx context.Context, userID int64) (GetExternalAccountRow, error)
	GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (IdempotencyKey, error)
	GetLatestSnapshot(ctx context.Context, accountID int64) (BalanceSnapshot, error)
	GetMonthlySummary(ctx context.Context, arg GetMonthlySummaryParams) (GetMonthlySummaryRow, error)
	GetSnapshotOnDate(ctx context.Context, arg GetSnapshotOnDateParams) (BalanceSnapshot, error)
	GetTransactionForUser(ctx context.Context, arg GetTransactionForUserParams) (GetTransactionForUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	// Claim an idempotency key. Returns no row when the key already exists;
	// callers then read the existing record with GetIdempotency.
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (IdempotencyKey, error)
	// Ledger entries for one account, newest first, keyset-paginated on
	// (occurred_at, posting id). Pass cursor values of 'infinity'/max id
	// for the first page.
	ListAccountEntries(ctx context.Context, arg ListAccountEntriesParams) ([]ListAccountEntriesRow, error)
	ListAccountsByUser(ctx context.Context, arg ListAccountsByUserParams) ([]ListAccountsByUserRow, error)
	ListAllAccountIDs(ctx context.Context) ([]int64, error)
	ListPostingsByTransaction(ctx context.Context, transactionID int64) ([]Posting, error)
	// Export rows are postings on the user's normal accounts; the offsetting
	// external legs would only duplicate every line.
	ListPostingsForMonth(ctx context.Context, arg ListPostingsForMonthParams) ([]ListPostingsForMonthRow, error)
	MarkIdempotencySuccess(ctx context.Context, arg MarkIdempotencySuccessParams) error
	// Balances are derived from postings by created_at (insertion time), not
	// occurred_at, so backdated entries can never fall behind a snapshot cutoff.
	SumPostingsSince(ctx context.Context, arg SumPostingsSinceParams) (int64, error)
	// Snapshot cutoff uses created_at to match SumPostingsSince semantics.
	SumPostingsUpTo(ctx context.Context, arg SumPostingsUpToParams) (int64, error)
	UpdateExportStatus(ctx context.Context, arg UpdateExportStatusParams) error
	UpsertBalanceSnapshot(ctx context.Context, arg UpsertBalanceSnapshotParams) error
}

var _ Querier = (*Queries)(nil)
