// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package repo

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPosting = `-- name: CreatePosting :one
INSERT INTO postings (transaction_id, account_id, amount_minor)
VALUES ($1, $2, $3)
RETURNING id, transaction_id, account_id, amount_minor, created_at
`

type CreatePostingParams struct {
	TransactionID int64
	AccountID     int64
	AmountMinor   int64
}

func (q *Queries) CreatePosting(ctx context.Context, arg CreatePostingParams) (Posting, error) {
	row := q.db.QueryRow(ctx, createPosting, arg.TransactionID, arg.AccountID, arg.AmountMinor)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AccountID,
		&i.AmountMinor,
		&i.CreatedAt,
	)
	return i, err
}

const createTransactionHeader = `-- name: CreateTransactionHeader :one
INSERT INTO transactions (user_id, currency, category_id, occurred_at, note, reversal_of)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, currency, category_id, occurred_at, note, reversal_of, created_at
`

type CreateTransactionHeaderParams struct {
	UserID     int64
	Currency   string
	CategoryID pgtype.Int8
	OccurredAt time.Time
	Note       pgtype.Text
	ReversalOf pgtype.Int8
}

type CreateTransactionHeaderRow struct {
	ID         int64
	UserID     int64
	Currency   string
	CategoryID pgtype.Int8
	OccurredAt time.Time
	Note       pgtype.Text
	ReversalOf pgtype.Int8
	CreatedAt  time.Time
}

func (q *Queries) CreateTransactionHeader(ctx context.Context, arg CreateTransactionHeaderParams) (CreateTransactionHeaderRow, error) {
	row := q.db.QueryRow(ctx, createTransactionHeader,
		arg.UserID,
		arg.Currency,
		arg.CategoryID,
		arg.OccurredAt,
		arg.Note,
		arg.ReversalOf,
	)
	var i CreateTransactionHeaderRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.CategoryID,
		&i.OccurredAt,
		&i.Note,
		&i.ReversalOf,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionForUser = `-- name: GetTransactionForUser :one
SELECT id, user_id, currency, category_id, occurred_at, note, reversal_of, created_at
FROM transactions
WHERE id = $1 AND user_id = $2
`

type GetTransactionForUserParams struct {
	ID     int64
	UserID int64
}

type GetTransactionForUserRow struct {
	ID         int64
	UserID     int64
	Currency   string
	CategoryID pgtype.Int8
	OccurredAt time.Time
	Note       pgtype.Text
	ReversalOf pgtype.Int8
	CreatedAt  time.Time
}

func (q *Queries) GetTransactionForUser(ctx context.Context, arg GetTransactionForUserParams) (GetTransactionForUserRow, error) {
	row := q.db.QueryRow(ctx, getTransactionForUser, arg.ID, arg.UserID)
	var i GetTransactionForUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.CategoryID,
		&i.OccurredAt,
		&i.Note,
		&i.ReversalOf,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountEntries = `-- name: ListAccountEntries :many
SELECT p.id AS posting_id,
       t.id AS transaction_id,
       p.account_id,
       p.amount_minor,
       t.currency,
       t.occurred_at,
       t.note,
       p.created_at
FROM postings p
JOIN transactions t ON t.id = p.transaction_id
WHERE p.account_id = $1
  AND (t.occurred_at, p.id) < ($2::timestamptz, $3::bigint)
ORDER BY t.occurred_at DESC, p.id DESC
LIMIT $4
`

type ListAccountEntriesParams struct {
	AccountID        int64
	CursorOccurredAt time.Time
	CursorPostingID  int64
	PageLimit        int32
}

type ListAccountEntriesRow struct {
	PostingID     int64
	TransactionID int64
	AccountID     int64
	AmountMinor   int64
	Currency      string
	OccurredAt    time.Time
	Note          pgtype.Text
	CreatedAt     time.Time
}

// Ledger entries for one account, newest first, keyset-paginated on
// (occurred_at, posting id). Pass cursor values of 'infinity'/max id
// for the first page.
func (q *Queries) ListAccountEntries(ctx context.Context, arg ListAccountEntriesParams) ([]ListAccountEntriesRow, error) {
	rows, err := q.db.Query(ctx, listAccountEntries,
		arg.AccountID,
		arg.CursorOccurredAt,
		arg.CursorPostingID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountEntriesRow
	for rows.Next() {
		var i ListAccountEntriesRow
		if err := rows.Scan(
			&i.PostingID,
			&i.TransactionID,
			&i.AccountID,
			&i.AmountMinor,
			&i.Currency,
			&i.OccurredAt,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostingsByTransaction = `-- name: ListPostingsByTransaction :many
SELECT id, transaction_id, account_id, amount_minor, created_at
FROM postings
WHERE transaction_id = $1
ORDER BY id
`

func (q *Queries) ListPostingsByTransaction(ctx context.Context, transactionID int64) ([]Posting, error) {
	rows, err := q.db.Query(ctx, listPostingsByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Posting
	for rows.Next() {
		var i Posting
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.AmountMinor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
