// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workers.sql

package repo

import (
	"context"
	"time"
)

const listAllAccountIDs = `-- name: ListAllAccountIDs :many
SELECT id FROM accounts WHERE is_active = TRUE ORDER BY id
`

func (q *Queries) ListAllAccountIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listAllAccountIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumPostingsUpTo = `-- name: SumPostingsUpTo :one
SELECT COALESCE(SUM(amount_minor), 0)::bigint AS total
FROM postings
WHERE account_id = $1
  AND created_at <= $2
`

type SumPostingsUpToParams struct {
	AccountID int64
	Cutoff    time.Time
}

// Snapshot cutoff uses created_at to match SumPostingsSince semantics.
func (q *Queries) SumPostingsUpTo(ctx context.Context, arg SumPostingsUpToParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumPostingsUpTo, arg.AccountID, arg.Cutoff)
	var total int64
	err := row.Scan(&total)
	return total, err
}
