name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Tidy
        run: go mod tidy
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
      - name: Test
        run: go test ./... -race -count=1

